se700/Models/ViewModels/HomeViewModel.cs
using se700.Models.RecipeModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace se700.Models
{
    /// <summary>
    /// Primary model managing the Index view
    /// </summary>
    public class HomeViewModel {
        public string SearchQuery { get; set; }
        public List<IRecipeModel> FrontPage { get; set; }
    }
}

se700/Controllers/HomeController.cs
using se700.DAL;
using se700.Models;
using se700.Models.RecipeModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using se700.Util;
using Newtonsoft.Json;

namespace se700.Controllers {
    public class HomeController : Controller {
        private CookingContext db = new CookingContext();


        [HttpGet]
        /// <summary>
        /// <para>RetrieveRecipe is used to retrieve either one or multiple recipes for use in updating autocomplete or when searching for a recipe</para>
        /// <param name="searchQuery">The name of the recipe we are looking for.</param>
        /// <param name="needSingleRecipe">To determine if we are retrieving a single recipe or not.</param>
        /// </summary>
        public ActionResult RetrieveRecipe(string searchQuery, Boolean needSingleRecipe) {
            List<RecipeModel> recipesToReturn = new List<RecipeModel>();
            // Instantiate list of recipes from db
            List<RecipeModel> recipes = db.Recipes.ToList();
            if (!needSingleRecipe) {
                foreach (RecipeModel recipe in recipes) {
                    // Perform fuzzy search
                    int difference = FuzzySearch.Compute(searchQuery, recipe.Name);

                    // Add to recipesToReturn if it matches fuzzy search criteria
                    if (difference < 20) {
                        recipesToReturn.Add(recipe);
                    }
                }

                // Serializing the list of recipes into a JSON object
                var list = JsonConvert.SerializeObject(recipesToReturn,
                    Formatting.None,
                    new JsonSerializerSettings() {
                        ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                    });

                return Content(list, "application/json");
            } else {
                foreach (RecipeModel recipe in recipes) {
                    if (String.Equals(recipe.Name, searchQuery, StringComparison.OrdinalIgnoreCase)) {

                        string recipeInJson = JsonConvert.SerializeObject(recipe,
                                        Formatting.None,
                                        new JsonSerializerSettings() {
                                            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                                        });
                        return Content(recipeInJson, "application/json");
                    }
                }
                return HttpNotFound();
            }

        }

        /// <summary>
        /// <para>Used to retrieve 3 unique recipes for the front page.</para>
        /// </summary>
        /// <param name="recipeList">Database of recipes to go through.</param> 
        /// <param name="dbLength">Used to determine number for boolean array.</param>
        /// <returns>List of recipes of length 3 to show on the front page.</returns>
        public List<IRecipeModel> DisplayRecipes(RecipeModel[] recipeList, int dbLength)
        {
            var frontPage = new List<IRecipeModel>();
            bool[] isDone = new bool[dbLength];
            var rand = new Random();

            while (frontPage.Count != dbLength)
            {
                int val = rand.Next(0, dbLength);
                if (!isDone[val])
                {
                    frontPage.Add(recipeList[val]);
                    isDone[val] = true;
                }
            }

            return frontPage;
        }

        /// <summary>
        /// Action controlling the main page of our application.
        /// </summary>
        /// <returns>View Result abstracted as an action result.</returns>
        public ActionResult Index() {
            var data = db.Recipes.ToArray();
            var m = new HomeViewModel() {
                SearchQuery = "Search for something tasty"
            };
            if (db.Recipes.Count() > 0)
            {
                var frontPage = DisplayRecipes(data, data.Length);
                m.FrontPage = frontPage;
            }

            return View(m);
        }

        /// <summary>
        /// Action rendering the about page
        /// </summary>
        /// <returns>About page implementation</returns>
        public ActionResult About() {
            ViewBag.Message = "Welcome to Cookinator. Your worry-free recipe guide.";

            return View();
        }

        /// <summary>
        /// Action method which navigates to the RecipeView and delegates control to the recipecontroller.
        /// </summary>
        /// <returns>ViewResult representing</returns>
        public ActionResult Recipe() {
            ViewBag.Message = "Your current recipe.";

            return View();
        }

        public ActionResult QuickUse() {
            ViewBag.Message = "How to use the application";

            return View();
        }
    }
}

se700/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using se700.DAL;
using se700.Models.RecipeModels;
using se700.Models.RecipeModels.Step;

namespace se700.Controllers {
    /// <summary>
    /// Class responsible for all the views involved with recipes
    /// </summary>
    public class RecipeController : Controller {
        // Recipe model information from database context
        private CookingContext db = new CookingContext();

        // GET: Recipe
        /// <summary>
        /// Index page for recipes, gets and lists all recipes in a list.
        /// </summary>
        /// <returns>ActionResult of recipepage.</returns>
        public ActionResult Index() {
            return View(db.Recipes.ToList());
        }

        // GET: Recipe/Details/5
        /// <summary>
        /// Gets the details for one specific recipe.
        /// </summary>
        /// <param name="id">The UUID of a recipe</param>
        /// <returns>The view specific view related to this recipe</returns>
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeModel recipeModel = db.Recipes.Find(id);
            if (recipeModel == null) {
                return HttpNotFound();
            }
            return View(recipeModel);
        }

        // GET: Recipe/Create
        /// <summary>
        /// Loads the create a recipe page.
        /// 
        /// This view is where users will go to create new recipes to be added
        /// to the system.
        /// </summary>
        /// <returns>View showing the recipe creation screen</returns>
        public ActionResult Create() {
            return View();
        }

        // POST: Recipe/Create
        /// <summary>
        /// POST call to database with recipe information from the recipe creation form
        /// 
        /// ID has been removed from this POSTback since we want the system to generate the ID
        /// to prevent malicious posting to existing entities.
        /// </summary>
        /// <param name="recipeModelDTO">Data transfer object representing the recipe</param>
        /// <returns>Redirection is handled by javascript</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Ingredients,Instructions")] RecipeModelDTO recipeModelDTO) {
            RecipeModel recipeModel = new RecipeModel();
            if (ModelState.IsValid) {
                recipeModel = new RecipeModel {
                    Name = recipeModelDTO.Name,
                    Ingredients = recipeModelDTO.Ingredients
                };
                // Pass up the timed/plain instructions
                if (recipeModelDTO.Instructions == null)
                    return new HttpNotFoundResult();

                for (int i = 0; i < recipeModelDTO.Instructions.Count; i = i + 2) {
                    if (recipeModelDTO.Instructions[i + 1] == "0") {
                        recipeModel.Instructions.Add(new PlainInstruction() {
                            Description = recipeModelDTO.Instructions[i],
                        });
                    } else {
                        recipeModel.Instructions.Add(new TimedInstruction() {
                            Description = recipeModelDTO.Instructions[i],
                            Time = (int) (double.Parse(recipeModelDTO.Instructions[i + 1]) * 60)
                        });
                    }
                }
                db.Recipes.Add(recipeModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recipeModel);
        }

        // GET: Recipe/Delete/5
        /// <summary>
        /// Returns the deletion view where the user asked to confirm if they want to delete the
        /// recipe.
        /// </summary>
        /// <param name="id">The model that is set to be deleted</param>
        /// <returns>The recipe deletion page</returns>
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeModel recipeModel = db.Recipes.Find(id);
            if (recipeModel == null) {
                return HttpNotFound();
            }
            return View(recipeModel);
        }

        // POST: Recipe/Delete/5
        /// <summary>
        /// Performs the deletion of an entity from the database.
        /// </summary>
        /// <param name="id">The id of the model that will be deleted</param>
        /// <returns>Recipe Index page</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            RecipeModel recipeModel = db.Recipes.Find(id);
            IEnumerable<AbstractInstruction> abstractInstructions = db.Recipes.Find(id).Instructions;
            foreach (var ins in abstractInstructions.ToList())
                db.Instructions.Remove(ins as PlainInstruction);
            db.Recipes.Remove(recipeModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Interactive(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeModel recipeModel = db.Recipes.Find(id);
            if (recipeModel == null) {
                return HttpNotFound();
            }
            return View(recipeModel);
        }
    }
}

se700/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Cookinator is a hands free cooking application. You can use our database or add your favourite recipes to begin your
    easy cooking experience. Timing long tasks and following instructions has <b>never</b> been easier!</p>

se700/Views/Home/Index.cshtml
@model se700.Models.HomeViewModel
@{
    ViewBag.Title = "Cookinator - Hands-free recipes";
}

@* Search Bar on main page *@
    <div class="row" id="search-bar">
        @using (Html.BeginForm("Details", "Recipe", FormMethod.Post, new { id = "search-form" })) {
            <div class="container-fluid">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div class="search-field-container">
                        <div class="recipe-search">
                            <input type="hidden" id="value-check" value="false" />
                            <input type="hidden" id="id" name="id" value="" />
                            @Html.TextBoxFor(m => m.SearchQuery, new {id = "search-input"})
                            <button id="search-button" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                            <div id="menu-container"></div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

@* Display random recipies from our database, ensuring no duplicates. *@
<div class="row">
    @if (Model.FrontPage != null)
    {
        int showRecipes = 3;
        int count = 0;

        foreach (var recipe in Model.FrontPage)
        {
            if (count < showRecipes)
            {
                var ingredientsList = recipe.Ingredients.ToArray();
                int showIngredients = 3;
                <div class="col-md-4">
                    <h2>@recipe.Name</h2>
                    @for (int i = 0; (i < recipe.Ingredients.Count && i < showIngredients); i++)
                    {
                        <p class="label-info ingredient-front-page">
                            @ingredientsList[i].Name
                        </p>
                    }
                    <p><a href="/Recipe/Details/@recipe.ID" class="btn btn-warning">Visit recipe</a></p>
                </div>
            }
            count++;
        }
    }
</div>

@section scripts {
    @Scripts.Render("~/Scripts/jquery-ui.min.js")
    @Scripts.Render("~/Scripts/home.js")
}

se700/Views/Home/QuickUse.cshtml
@using se700.Models
@* @model SomeViewModel *@
@{ 
    ViewBag.Title = "Quick Use Guide";
}

<head>
    @Styles.Render("~/Content/Site.css");
</head>

<h1>@ViewBag.Title</h1>
<div class="row">
    <div class="container-fluid">
        <div class="col-sm-4 col-md-4 col-lg-4 col-sm-offset-1 col-lg-offset-1 col-mg-offset-1">
            <div id="prev-action">
                <h3>Previous</h3>
                <div class="img-container">
                    <img src="~/Content/Images/swipe-left.png" />
                </div>
            </div>
        </div>
        
        <div class="col-sm-4 col-md-4 col-lg-4">
            <div id="interact-action">
                <h3>Interact</h3>
                <div class="img-container">
                    <img src="~/Content/Images/hand-still.png" />
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-3 ">
            <div id="next-action">
                <h3>Next</h3>
                <div class="img-container">
                    <img src="~/Content/Images/swipe-right.png" />
                </div>
            </div>
        </div>
    </div>
</div>                

<div class="row">
    <div class="container-fluid">
        <div class="col-sm-6 col-sm-offset-5 col-md-6 col-md-offset-5 col-lg-6 col-lg-offset-5">
            <div id="down-action">
                <h3>Down</h3>
                <div class="img-container">
                    <img src="~/Content/Images/swipe-down.png" />
                </div>
            </div>
        </div>
    </div>
</div>